### ISSUE TITLE
Issues with the generation of PDF from the SIP spec Markdown

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/spec-publisher#1]
## Front page and authors missing

![Screenshot 2019-05-31 at 11 45 25](https://user-images.githubusercontent.com/3181302/58700994-9dab6080-8399-11e9-92e2-9a197ac470e3.png)

## Biblio items showing up on TOC

![Screenshot 2019-05-31 at 11 46 15](https://user-images.githubusercontent.com/3181302/58701029-b3b92100-8399-11e9-873b-d8496ee2a2e4.png)

## There is a reference to an appendix 1 that is not being included. I recommend putting the authors in this section instead of an appendix.

Appendixes are numbered as A, B, C, not numbers.

![Screenshot 2019-05-31 at 11 47 54](https://user-images.githubusercontent.com/3181302/58701098-eebb5480-8399-11e9-877a-20655b1d7a3f.png)

## Conversion from METS profile to MD is not preserving the break lines

![Screenshot 2019-05-31 at 11 49 15](https://user-images.githubusercontent.com/3181302/58701164-1f02f300-839a-11e9-8ed7-a06a376aadfd.png)

## IDs are being cut on tables

![Screenshot 2019-05-31 at 11 49 48](https://user-images.githubusercontent.com/3181302/58701229-3f32b200-839a-11e9-9cd2-893107a49d01.png)

## Suggestion: Reduce the width of the column on the right 

![Screenshot 2019-05-31 at 11 51 53](https://user-images.githubusercontent.com/3181302/58701324-802ac680-839a-11e9-94d7-4b432e59cbe9.png)

## Controlled vocabularies not being rendered in the nicest way

![Screenshot 2019-05-31 at 11 59 52](https://user-images.githubusercontent.com/3181302/58701762-c03e7900-839b-11e9-9ab9-249562c038e3.png)

## Column being cut off

![Screenshot 2019-05-31 at 12 00 28](https://user-images.githubusercontent.com/3181302/58701746-b0bf3000-839b-11e9-87e4-9de14d0caf95.png)

## version number is missing on the footer

![Screenshot 2019-05-31 at 12 01 19](https://user-images.githubusercontent.com/3181302/58701788-d5b3a300-839b-11e9-9501-8caf71293b54.png)

## Ref missing???

![Screenshot 2019-05-31 at 12 01 43](https://user-images.githubusercontent.com/3181302/58701800-dcdab100-839b-11e9-9e87-a10d5fa3d30a.png)

## Front page is at the bottom of the document

<img width="1209" alt="Screenshot 2019-05-31 at 12 05 06" src="https://user-images.githubusercontent.com/3181302/58701958-570b3580-839c-11e9-929c-16b3791a8957.png">

**Comment by carlwilson** [comment]
@jmaferreira I have just gone through these and I suspect that only the attribute formatting for XML is still an issue here now. I you could confirm, I'll see what can be done about the formatting.

**Comment by jmaferreira** [comment]
Hi @carlwilson, can you please point me in the direction of the latest generated version so I can check?

**Comment by carlwilson** [comment]
Hi, @jmaferreira this came up as part of the imminent (today) 2.0.4 release, will point you at that when it's ready.

**Comment by carlwilson** [comment]
I think that these are in hand/understood and this can be closed @jmaferreira ?
