### ISSUE TITLE
Update in image due to name change of CITS Geodata

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/spec-publisher#13]
CITS Geodata got renamed to "Specification for digital geospatial data records archving" this needs to be reflected in the image.

[https://github.com/DILCISBoard/spec-publisher/blob/master/res/md/figs/fig_1_dip.svg](https://github.com/DILCISBoard/spec-publisher/blob/master/res/md/figs/fig_1_dip.svg)

**Comment by DrJaime** [comment]
![fig_1_dip](https://user-images.githubusercontent.com/39824002/83289477-06136480-a1dd-11ea-977e-6c20550adf3d.png)

Image updated - replacing geodata with 'digital geospatial data records'
